name: Doxygen Deployment

on:
  push:
    branches:
      - rolling
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  doxygen_generation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Doxygen for EasyNav
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: ".github/Doxyfile"

      - name: Doxygen Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/html
