name: Doxygen Deployment

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
      - cron: '0 0 * * 6'     

jobs:
  doxygen_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Doxygen for easynav
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: ".github/Doxyfile"
